export const SEARCH_NEWS_LIST_REQUEST = "SEARCH_NEWS_LIST_REQUEST";
export const SEARCH_NEWS_LIST_SUCCESS = "SEARCH_NEWS_LIST_SUCCESS";
export const SEARCH_NEWS_LIST_FAILURE = "SEARCH_NEWS_LIST_FAILURE";
export const GET_KEYWORD_LIST_REQUEST = "GET_KEYWORD_LIST_REQUEST";
export const GET_KEYWORD_LIST_SUCCESS = "GET_KEYWORD_LIST_SUCCESS";
export const GET_KEYWORD_LIST_FAILURE = "GET_KEYWORD_LIST_FAILURE";
