export const SEARCH_NEWS_LIST_REQUEST = "SEARCH_NEWS_LIST_REQUEST";
export const SEARCH_NEWS_LIST_SUCCESS = "SEARCH_NEWS_LIST_SUCCESS";
export const SEARCH_NEWS_LIST_FAILURE = "SEARCH_NEWS_LIST_FAILURE";
